"""First migration

Revision ID: 20c9c44fc1a4
Revises: 4d499038aeb8
Create Date: 2023-08-18 19:45:32.897012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20c9c44fc1a4'
down_revision = '4d499038aeb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
